name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
    - name: make test
      run: |
        make test -C 3_Implementation/
    - name: make coverage
      run: |
        make coverage -C 3_Implementation/
